language: ruby
rvm:
- 2.2.0
notifications:
  email:
    recipients: corbel-dev@bq.com
    on_success: change
    on_failure: never
before_install:
- npm install -g bower
- gem install bundler
install:
- bower install
- bundle install
script:
- bundle exec jekyll build
- bash ./travis-runner.sh
branches:
  only:
  - master
env:
  global:
    secure: Aga7gQ1q5LOUyxcwJyDzGU/egj6vBJUT8kFv1rrb6h7RCCJXVrjkgaGa1o5oAvJmDSRO7g8D7gmTF0zWEHOsxguU5em0rzlG0G7sE4jLg/tOp+pAbuuRL5PWPAKkrAuoA+TWISrg3ejoa6b4XxSM9kN1m/Og7t323BvXBxuhcRRh3AW+DgdE4x5XV3OeT/VIRplk2BcH0SuaR3Hoo7ioAeFV2QPJPxbs3HoWmVtzrBcFAotV5Zd1XAeZEoQ5GuM0FICOeyPo+1M4gK/GH7V5apnBoQ/m+GWEn0gdZQ/3r5Q1YjBnRdKOp8uNSPmuQcdeAemXJKuCw5GpRYLNYWcYpv6S/t9/GgacLk3zERc/+Yg6qnXqf6S0VAjameyI/3dRS641v1zmJRYXxv/DHu9Guka//UWBBCBKmtfPJ1K7+4FPErSIs4P2AKOogYC70kXb0+MlYm16F08nx7szCB+/1kav+BndlwFwohWZeJN1R1FCwNHTet6RYAZyzyqL1tvP6fATL+7ak/+Oa7WlC6oW2F85OK1da/qo2IRnHZqMyZte9I0IrS2lHmZdSrawRJMGtSPkStax8JoAoXDddaz+Vu3aC9udiIiyZkgHVCML+O0juYKIIJI0VhcyC2kYMuqONHynnPVECx8UusVeXK9MfP8HGiLeqj2JNBkGOONUgc4=
