
# Site settings
title: Corbel
email: corbel-dev@bq.com
description: Corbel platform is a generic platform that offers you all you need to build any application such as authentication, resources or events.
baseurl: ""
url: "https://corbel.io"


# Social user names
twitter_username: corbel_platform
github_username:  corbel_platform


# Custom collections
collections:
  components:
    output: true
    permalink: /components/:path/


# Build settings
markdown: kramdown


# Sass configuration
sass:
  sass_dir: assets/css
  style: compressed


# Plugins
whitelist: []
gems:      [susy, breakpoint]


# Include files
include: ['_pages']


# Exclude files
exclude: [travis-runner.sh, bower.json, editorconfig, Gemfile, Gemfile.lock, ./**/*.scss]
